#!/bin/bash
# runsvr
# This service has been registered on remote.io a/c with 
# hostname proxy72.rt3.io and port # 30193  (60001 in little endian)
svr=cpudtl_tstsvr
pgrep ${svr} && {
 echo "server ${svr} is already running..."
 exit 1
}
./${svr} 0.0.0.0 60001 -v &

#--- Client:
# Now connect from the client to the server process like this:
# 1. On the local network (LAN):
#  nc <any-ipaddr-on-client> <port#>
# f.e.
#  nc 192.168.1.201 60001
#
# 2. If using an IoT service (like remote.it)
#  nc -v proxy72.rt3.io 30193   
# -or-
#  ./client_any proxy72.rt3.io 30193   
