#!/bin/bash
name=${0##*/}
die()
{
  echo -e >&2 "${name}:FATAL: $*"
  exit 1
}

[ $# -ne 2 ] && die "Usage: ${name} PID name-of-mapping
  Eg. $0 1001 stack"
sudo kill -0 $1 || die "process PID $1 doesn't exist?"
sudo grep $2 /proc/$1/maps >/dev/null || die "no match for $2 in process maps file"
END=$(sudo grep "\[$2\]" /proc/$1/maps |cut -f1 -d' '|cut -f2 -d'-')
START=$(sudo grep "\[$2\]" /proc/$1/maps |cut -f1 -d' '|cut -f1 -d'-')
size_hex=$(printf "0x%x\n" $((0x${END} - 0x${START})))
size=$((size_hex))
echo ${size}
