#!/bin/bash
# runsvr
# This service has been registered on remote.io a/c with 
# hostname proxy72.rt3.io and port # 30193  (60001 in little endian)
svr=cpudtl_tstsvr
port=60001
pgrep ${svr} && {
 echo "server ${svr} is already running..."
 exit 1
}
grep -w ${port} /etc/services && {
 echo "port # $port} is already in use..."
 exit 1
}
./${svr} ${port} -v &

#--- Client:
# Now connect from the client to the server process like this:
# 1. On the local network (LAN):
#  nc <any-ipaddr-on-client> <port#-of-server>
# f.e.
#  nc 192.168.1.201 60001
#
# 2. If using an IoT service (like remote.it)
#  nc -v <proxy-addr> <port#>   
# -or-
#  ./client_any <proxy-addr> <port#>   
