#!/bin/bash
name=$(basename $0)
[ $# -ne 1 ] && {
  echo "Usage: ${name} systemd-unit-file"
  exit 1
}

DEFAULT_TGT=multi-user.target

die()
{
  echo "$*" 1>&2; exit 1
}

UNITFILE=$1
[ ! -f ${UNITFILE} ] && die "${UNITFILE} not found"
sudo cp ${UNITFILE} /lib/systemd/system/
echo "Enable and run it NOW"
sudo systemctl enable --now ${UNITFILE} || die "enabling svc failed"
#journalctl -k -f
ls -l /lib/systemd/system/${DEFAULT_TGT}.wants/${UNITFILE} 2>/dev/null
[[ $? -ne 0 ]] && ls -l /etc/systemd/system/${DEFAULT_TGT}.wants/${UNITFILE}
exit 0
