#!/bin/bash

[[ $# -ne 1 ]] && {
	echo "Usage: ${name} number-of-client-processes-to-run"
	exit 1
}
MAX=$1
CLIENT=client_sem_as_counting
for i in $(seq 1 ${MAX})
do
	MSG="client msg $i"
	echo "CLIENT:  \"${MSG}\""
	./${CLIENT} "client msg $i"
done
