name: compile_and_test_1

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build & test Lamscript on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [ g++-10 ]
        include:
          - os: ubuntu-latest
            compiler: g++-10
            target: Linux

          - os: macos-latest
            compiler: g++-10
            target: Macos

          - os: windows-latest
            compiler: cl
            target: Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the projects setup.
        run: ./scripts/setup.sh --within-ci true

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Compile a release build of lamscript
        run: ./scripts/compile_lamscript.sh \
            --build Release \
            --cpp-compiler ${{ matrix.compiler }} \
            --os ${{ matrix.target }}
            --cores 2

      - name: Run all of lamscripts tests.
        run: ./scripts/run_all_tests.sh --build Release --os ${{ matrix.target }}
